// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserHandle : RemoteTableHandle<EventContext, User>
        {
            protected override string RemoteTableName => "User";

            public sealed class IdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(User row) => row.Id;

                public IdUniqueIndex(UserHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal UserHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(User row) => row.Id;
        }

        public readonly UserHandle User;
    }
}
