// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message
    {
        [DataMember(Name = "SenderId")]
        public SpacetimeDB.Identity SenderId;
        [DataMember(Name = "Timestamp")]
        public SpacetimeDB.Timestamp Timestamp;
        [DataMember(Name = "Text")]
        public string Text;

        public Message(
            SpacetimeDB.Identity SenderId,
            SpacetimeDB.Timestamp Timestamp,
            string Text
        )
        {
            this.SenderId = SenderId;
            this.Timestamp = Timestamp;
            this.Text = Text;
        }

        public Message()
        {
            this.Text = "";
        }
    }
}
