// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User
    {
        [DataMember(Name = "Id")]
        public SpacetimeDB.Identity Id;
        [DataMember(Name = "Name")]
        public string? Name;
        [DataMember(Name = "Online")]
        public bool Online;

        public User(
            SpacetimeDB.Identity Id,
            string? Name,
            bool Online
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Online = Online;
        }

        public User()
        {
        }
    }
}
